### ISSUE TITLE
Question: REST API Store

### ISSUE THREAD

**Issue by hacfi** [webmozart/key-value-store#5]
Does it make sense to add a REST API Store? Maybe using guzzlehttp or adding an interface for the client.

Just thought of this while visiting https://github.com/begriffs/postgrest

**Comment by webmozart** [comment]
Why not? :) I guess it's hard though to write a generic store that is not tied to a specific service.

**Comment by eljam** [comment]
Hi @hacfi,
i'm currently writing a bundle that wrap this library with a REST API on top of it. I don't know if you found a solution yet but it's gonna be online in a couple of weeks.

**Comment by webmozart** [comment]
Thanks for sharing @eljam! I'm closing this issue. Nobody needed this for now and I don't think this actually belongs in here.
