### ISSUE TITLE
What about a 'remember' method?

### ISSUE THREAD

**Issue by terah** [webmozart/key-value-store#6]
See here for what I mean: https://github.com/terah/cache-pools/blob/master/src/CachePools.php#L135

**Comment by webmozart** [comment]
What's the benefit of that method in a key-value store context? (see also [the README] for a differentiation between caches and key-value stores)

[the README]: https://github.com/webmozart/key-value-store/blob/master/README.md

**Comment by terah** [comment]
Yes.. this is something that I'd like in a cache interface and has less value in a key/value interface.  Please close.

**Comment by webmozart** [comment]
Ok :)
