### ISSUE TITLE
Implement Countable where possible

### ISSUE THREAD

**Issue by webmozart** [webmozart/key-value-store#7]
KeyValueStore implementations should implement Countable, where possible.

**Comment by tgalopin** [comment]
Here are what I have in mind:

- `ArrayStore` and `JsonFileStore` are easily countable ;
- `NullStore` has the method and it should return zero ;
- `CachedStore` is countable and call the delegated store `count()` ;
- `PhpRedisStore` and `PredisStore` call LLEN (http://redis.io/commands/LLEN) ;
- `RiakStore` count keys using a stream (http://lists.basho.com/pipermail/riak-users_lists.basho.com/2011-November/006636.html) ;

Perhaps could the `CachedStore` store the count result in its cache with a special key. What do you think?

**Comment by tgalopin** [comment]
On the same idea than https://github.com/webmozart/key-value-store/issues/8#issuecomment-119250804, we could have a CountableDecorator for uncountable repositories (like Riak). What do you think?

**Comment by webmozart** [comment]
Yes, let's do that!

**Comment by tgalopin** [comment]
I think we can close that now :) .
